### ISSUE TITLE
IMvc Builder doesn't contain definition for AddModelBindingMessagesLocalizer

### ISSUE THREAD

**Issue by geommr** [LazZiya/MyTrips#1]
.AddModelBindingMessagesLocalizer(services) chained call in startup.cs ([line](https://github.com/LazZiya/MyTrips/blob/7d059ed4f96c3bc5253a42cb61e6dafe0e8cd8a8/MyTrips/Startup.cs#L40)) throws an error. Was the function renamed or deprecated?

**Comment by LazZiya** [comment]
This is an extension method inside "[Utilities/MvcOptionsExtension.cs](https://github.com/LazZiya/MyTrips/blob/7d059ed4f96c3bc5253a42cb61e6dafe0e8cd8a8/MyTrips/Utilities/MvcOptionsExtension.cs#L17)" file.

Make sure that you have the reference in startup.cs

@using MyTrips.Utilities

If you are implementing the localization steps on your own solution you can copy the method to your project.

**Comment by geommr** [comment]
Yeah, this is implemented later on, but was mentioned in an earlier step. Thanks for the quick response!
