### ISSUE TITLE
How implement in web api?

### ISSUE THREAD

**Issue by majid23** [LazZiya/MyTrips#3]
hi Ziya
thanks for your repository.
I use 

> [Localize request via according to provided route value](http://ziyad.info/en/articles/12-Configuring_Culture_Route_Model)

 article
```
    [Route("{culture?}/api/[controller]")]
    [ApiController]
    public class UsersController : ControllerBase
    {
        [HttpGet]
        public async Task<IActionResult> GetUsers()
        {
               ...
       }
    }
```

In this code i can not request http://localhoat:5000/api/users
I just can request http://localhoat:5000/tr/api/users.

how can i solve this problem until http://localhoat:5000/api/users response to me. this url in situation send not found.

thanks.

**Comment by LazZiya** [comment]
Hi Majid,

Add a second route convention to the controller without `{culture}`, so if there is no culture is found, the second route will match the requested url : 

````cs
[Route("{culture}/[controller]")]
[Route("[controller]")]
[ApiController]
public class UsersController : ControllerBase
{
    [HttpGet]
    public async Task GetUsers()
    {
        ...
    }
}
````
