### ISSUE TITLE
Change Resources

### ISSUE THREAD

**Issue by MahdiElahi** [LazZiya/MyTrips#4]
i want change resource text for a language 
how can i access to LazZiya.ExpressLocalization to add new item ? 
and 
what do you do in localize-content ? its lock

**Comment by LazZiya** [comment]
All resources are under [`Resources`](https://github.com/LazZiya/MyTrips/tree/master/MyTrips/Resources) folder, you can add/change any culture under that folder.

Re `localize-content`, I'm not sure if I clearly understood the question, but it is not used in this project! instead it is a part of [LazZiya.ExpressLocalization](https://github.com/lazziya/ExpressLocalization) nuget package and used to easily localize views using html tags. 

For more info see [sample project](https://github.com/lazziya/ExpressLocalizationSampleCore3) and full [documentation](https://github.com/lazziya/ExpressLocalization/wiki).

**Comment by LazZiya** [comment]
@MahdiElahi I hope my reply has answered your question, if not feel free to reopen the issue.

best,
Ziya
